blueprint:
  name: Superloop Usage Alert
  description: >
    Sends a persistent notification when your Superloop data usage reaches 90% of your plan's allowance.
    Skips plans with unlimited data.
  domain: automation
  input:
    usage_sensor:
      name: Data Usage Sensor
      description: Select your Superloop Free Download Usage sensor (e.g., sensor.superloop_free_download_usage).
      selector:
        entity:
          domain: sensor

    allowance_sensor:
      name: Plan Allowance Sensor
      description: Select your Superloop Plan Allowance sensor (e.g., sensor.superloop_plan_allowance).
      selector:
        entity:
          domain: sensor

trigger:
  - platform: numeric_state
    entity_id: !input usage_sensor
    above: 0

condition:
  - condition: template
    value_template: >
      {% set usage = states(usage_sensor) %}
      {% set allowance = states(allowance_sensor) %}
      {% if not usage or not allowance %}
        false
      {% elif 'Unlimited Data' in allowance %}
        false
      {% else %}
        {% set current = usage | float %}
        {% set limit = allowance.replace('GB', '') | float %}
        {{ current >= (limit * 0.9) }}
      {% endif %}

action:
  - service: persistent_notification.create
    data:
      title: "Superloop Usage Warning"
      message: >
        Your data usage has reached 90% of your plan allowance!
        Current usage: {{ states(usage_sensor) }} GB out of {{ states(allowance_sensor) }}.

mode: single
