blueprint:
  name: Superloop Usage Alert
  description: >
    Sends (or updates) a persistent notification when your Superloop
    data usage reaches 90% of your plan allowance.
    Skips plans with “Unlimited Data.”
  domain: automation
  version: 1

  input:
    usage_sensor:
      name: Data Usage Sensor
      description: Your Superloop download usage sensor
      selector:
        entity:
          domain: sensor

    allowance_sensor:
      name: Plan Allowance Sensor
      description: Your Superloop plan allowance sensor
      selector:
        entity:
          domain: sensor

trigger_variables:
  # expose your inputs as simple vars
  usage_sensor: !input usage_sensor
  allowance_sensor: !input allowance_sensor

trigger:
  - platform: state
    # fire on ANY change to your usage sensor
    entity_id: "{{ usage_sensor }}"

condition:
  # 1) skip if your plan is Unlimited Data
  - condition: not
    conditions:
      - condition: state
        entity_id: "{{ allowance_sensor }}"
        state: "Unlimited Data"

  # 2) skip if usage hasn’t populated yet
  - condition: template
    value_template: >
      {{ states(usage_sensor) not in ['unavailable', 'unknown'] }}

  # 3) skip if allowance hasn’t populated yet
  - condition: template
    value_template: >
      {{ states(allowance_sensor) not in ['unavailable', 'unknown'] }}

  # 4) only proceed when usage ≥ 90% of allowance
  - condition: template
    value_template: >
      {% set current = states(usage_sensor) | float %}
      {% set limit = (states(allowance_sensor)
                        | regex_replace(find='[^0-9.]', replace='')
                        | float) %}
      {{ current >= (limit * 0.9) }}

action:
  - service: persistent_notification.create
    data:
      notification_id: superloop_usage_warning
      title: "Superloop Data Usage Warning"
      message: >
        Your data usage has reached 90% of your plan allowance!  
        Current usage: {{ states(usage_sensor) }} GB  
        Plan allowance:  {{ states(allowance_sensor) }} GB

mode: single
