blueprint:
  name: Superloop Usage Alert
  description: >
    Sends (or updates) a persistent notification when your Superloop
    data usage reaches 90% of your plan allowance.
    Skips plans with “Unlimited Data.”
  domain: automation

  input:
    usage_sensor:
      name: Data Usage Sensor
      description: Select your Superloop download usage sensor
      selector:
        entity:
          domain: sensor

    allowance_sensor:
      name: Plan Allowance Sensor
      description: Select your Superloop plan allowance sensor
      selector:
        entity:
          domain: sensor

trigger:
  - platform: state
    entity_id: !input usage_sensor

condition:
  - condition: template
    value_template: >
      {% set usage_str = states(input.usage_sensor) %}
      {% set allowance_str = states(input.allowance_sensor) %}

      {% if not usage_str or not allowance_str %}
        false
      {% elif 'Unlimited Data' in allowance_str %}
        false
      {% else %}
        {% set current = usage_str | float %}
        {% set limit = (allowance_str | regex_replace(find='[^0-9.]', replace='')) | float %}
        {{ current >= (limit * 0.9) }}
      {% endif %}

action:
  - service: persistent_notification.create
    data:
      notification_id: superloop_usage_warning
      title: "Superloop Data Usage Warning"
      message: >
        Your data usage has reached 90% of your plan allowance!  
        Current usage: {{ states(input.usage_sensor) }} GB  
        Plan allowance: {{ states(input.allowance_sensor) }} GB

mode: single
