# Superloop Services
refresh_data:
  name: Refresh Data
  description: Manually refresh the Superloop data from the API
  
refresh_token:
  name: Refresh Token
  description: Manually refresh the Superloop authentication token